### ISSUE TITLE
Invalid Handle for Console

### ISSUE THREAD

**Issue by ted-dgk** [noseratio/coroutines-talk#1]
When I run I get "Invalid Handle Exception" for the very first access to Console in Main. May have to do with use of Forms? Tried various project settings and other things and no help. Up to date on VS and SDK's.

Thanks
Ted

**Comment by noseratio** [comment]
Interesting, I can confirm it now happens when I set `Console.Title`, and and the problem doesn't going away even if I set the app type to `Console Application`. That wasn't happening with .NET 3.1.x at the time I was demo'ing it. 

![image](https://user-images.githubusercontent.com/4774875/110179311-f1df5080-7e5b-11eb-90f4-b3dff3ecd401.png)
 
I've fixed it by calling `AllocConsole` at the very beginning, a PR is coming up. Thanks for reporting!
